[#375] add support for setting plantuml.include.path
asciidoctor/asciidoctor-diagram-java pull request #7
Opened 2021-11-14 21:09 UTC by mskyaxl

See https://github.com/asciidoctor/asciidoctor-diagram/issues/375

2021-11-16 14:08 UTC, pepijnve requested changes

2021-11-16 14:08 UTC, pepijnve commented on plantuml/src/main/java/org/asciidoctor/diagram/plantuml/PlantUMLPreprocessor.java
> +        String includeDir = request.headers.getValue("X-PlantUML-IncludeDir");
Are there any other options to set the include dir than a system property? It would be nice if we could implement this without setting global state that can leak from one run to the next one.

2021-11-16 14:08 UTC, pepijnve commented on plantuml/src/main/java/org/asciidoctor/diagram/plantuml/PlantUMLPreprocessor.java
> +        String includeDir = request.headers.getValue("X-PlantUML-IncludeDir");
Like most things in the PlantUML codebase it looks like it's messy and there's no easy way to override the behaviour. What we'll need to do then is put the whole thing in synchronised and try/finally where we restore the old value of the system property.

2021-11-16 18:22 UTC, mskyaxl commented on plantuml/src/main/java/org/asciidoctor/diagram/plantuml/PlantUMLPreprocessor.java
> +        String includeDir = request.headers.getValue("X-PlantUML-IncludeDir");
Updated :), please have a look.

2021-11-19 07:41 UTC, pepijnve approved these changes

2021-11-19 07:41 UTC, merged